version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.19.3
    commands:
      - npm install

artifacts:
  files:
    - app.js
    - package.json
    - public/**
    - .ebextensions/**
  discard-paths: no