version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.19.3
    commands:
      - echo Installing root dependencies...
      - cd server
      - npm install
      - cd ..
  pre_build:
    commands:
      - echo Installing frontend dependencies...
      - cd client
      - npm install
      - cd ..
  build:
    commands:
      - echo Building React frontend...
      - cd client
      - npm run build
      - cd ..
      - echo Copying React build to server...
      - rm -rf server/build
      - cp -r client/build server/build
  post_build:
    commands:
      - echo Zipping server for EB deployment...
      - cd server
      - zip -r ../app.zip ./*
      - cd ..

artifacts:
  files:
    - app.zip
