version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.19.3
    commands:
      - echo Installing backend dependencies...
      - npm install --prefix server
      - echo Installing frontend dependencies...
      - npm install --prefix client
  build:
    commands:
      - echo Building React frontend...
      - npm run build --prefix client
      - echo Copying React build to server...
      - rm -rf server/build
      - cp -r client/build server/build
  post_build:
    commands:
      - echo Zipping server for EB deployment...
      - zip -r app.zip server/*

artifacts:
  files:
    - app.zip
